pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        dockerContainer {
          image 'maven:3.8.1-adoptopenjdk-11'
        }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        dockerContainer {
          image 'node:16-alpine'
        }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
